### ISSUE TITLE
Required extension 'curl' not found

### ISSUE THREAD

**Issue by web-ap** [easyphp/DEVSERVER#69]
Hi,

I'm trying to install a php script which requires cURL. I have a fresh install of the lastest easyphp (with php 7) and I obtain an error 

> Required extension 'curl' not found

curl is activated in php.ini and here is the log error : 

> PHP Warning: PHP Startup: Unable to load dynamic library 'C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-binaries\php\php704vc14x86x160521084858\ext\php‌​_curl.dll' - Le module sp\xef\xbf\xbdcifi\xef\xbf\xbd est introuvable.\r\n in Unknown on line 0

The file php_curl.dll is well placed in ext folder.

What should I do?

Thanks.

**Comment by StaggerLeee** [comment]
Some scripts detect Curl as running, some not. PHP Info file gives as it is activated. Yet I have seen scripts complaining it is not activated in PHP.

**Comment by bgatellier** [comment]
[According to the PHP doc](http://php.net/manual/en/curl.installation.php), Windows must be aware of two additional libraries (_libeay32.dll_ and _ssleay32.dll_). This can be achieve by adding the path to these libraries into the PATH environment variable.

Furthermore, you could find in the PHP doc [a list of all the dll dependencies](http://ca1.php.net/manual/en/install.windows.extensions.php) for each php extension.

**Comment by StaggerLeee** [comment]
I know. 
EasyPHP should register all paths under installation. Later all installed modules can do the same.It is not easy at all to do it right in Windows.

**Comment by bgatellier** [comment]
Well, the registration would be great if EasyPHP is running with only one PHP version.

But in the case where you have more than one PHP installed, and especially if some versions run in x86 and others in x64, this behavior would not help at all (because the libraries are different).

But whatever the solution, the documentation should be improved. Maybe we can help you with that @easyphp ?

**Comment by CyrilCharlier** [comment]
the wiki is available, we can improve it ;)
https://github.com/easyphp/easyphp-devserver/wiki

**Comment by bgatellier** [comment]
@CyrilCharlier I just updated [the FAQ page](https://github.com/easyphp/easyphp-devserver/wiki/FAQ), so feel free to review it (and correct my far-from-perfect english ;-))

**Comment by CyrilCharlier** [comment]
Hi @bgatellier , i'm not english too but french and i'm not the developper of notepad++ ;) i just suggest :)

**Comment by StaggerLeee** [comment]
Non of it will help it. I tried all.

Only to download curl with curl.exe for Windows and put files (not folder) inside windows - System32, and SysWOW64 folder. After this Windows takes care of everything by itself.

**Comment by CyrilCharlier** [comment]
so @StaggerLeee you can update [the FAQ page](https://github.com/easyphp/easyphp-devserver/wiki/FAQ) ;)

**Comment by StaggerLeee** [comment]
Just copy / paste this Info:
http://www.ehow.com/how_8745336_install-curl-easyphp.html

**Comment by bgatellier** [comment]
Hi @StaggerLeee,

Modify any system folder is not recommended for consistency, compatibility and clarity reasons. It is like any CMS: if you want to add a feature, you will add a plugin, but not change the core itself.

So I did a fresh new installation of EasyPHP, removed my previous environment variables and try to make it work again. Here are the steps:
1. Add the path to your PHP folder to the _Path_ environment variables (so the system will be aware of the required dependencies like extra dll)
2. Uncomment the line `extension=php_curl.dll` from the php.ini file
3. Restart EasyPHP (only restarting Apache will not take into account step 1)
4. [Optional] If you were using php in the console, you have to close it and start a new one in order to take into account the changes from step 1

I will add these steps to the FAQ

**Comment by StaggerLeee** [comment]
I did not restart EasyPHP dashboard. Maybe that was problem.

**Comment by bgatellier** [comment]
I'm not part of the team, so the choice does not belong to me ;-)
But if the team is open to propositions or at least discussions, this could be a subject.

**Comment by JigSawFr** [comment]
Same problem, thanks for your setps @bgatellier 
I will add the fact you need to put in SYSTEM -> PATH environnement variable (and not USER -> PATH).
And if you want to use a specific php version in CLI, reorder php paths in PATH vars, the first will be use.

**Comment by bgatellier** [comment]
@JigSawFr I assume that you are running a different PHP configuration for each project.
So it makes sense to have a PHP CLI for each project too, in order to share the same php.ini configuration.
In that case, create 2 symbolic links to _php.exe_ and _php.ini_ in each folder, related to the files in the  PHP folder you're using.
You will loose the system registration of the command, but it will avoid this reordering thing each time you want to switch from one PHP version to another.
